name         'stdmod-wget'
version      '0.0.1'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-wget'
summary      'Puppet module for wget'
description  'This module installs and manages wget. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
